#!/usr/bin/env node
import { Command } from "commander";
import chalk from "chalk";
import ora from "ora";
import path from "path";
import fs from "fs-extra";
import { execa } from "execa";
import { glob } from "glob";
import prompts from "prompts";

// ─── Registry ─────────────────────────────────────────────────────────────────

const REGISTRY_BASE = "https://raw.githubusercontent.com/frosted-ui/frosted-ui/main/registry";

const COMPONENTS = [
  "floating-island-bar",
  "expandable-nav-sheet",
  "pill-bar",
  "pebble-bar",
  "wave-bar",
  "crystal-bar",
  "arc-bar",
  "ribbon-bar",
  "dock-bar",
  "app-launcher",
  "command-sheet",
  "profile-sheet",
  "floating-search-orb",
  "floating-action-button",
  "floating-command-bar",
] as const;

type ComponentName = typeof COMPONENTS[number];

// ─── Project Detection ────────────────────────────────────────────────────────

interface ProjectConfig {
  root: string;
  framework: "nextjs" | "vite" | "remix" | "unknown";
  typescript: boolean;
  tailwind: boolean;
  srcDir: boolean;
  componentsDir: string;
  packageManager: "npm" | "pnpm" | "yarn" | "bun";
}

async function detectProject(cwd: string): Promise<ProjectConfig> {
  const pkg = await fs.readJson(path.join(cwd, "package.json")).catch(() => ({}));
  const deps = { ...pkg.dependencies, ...pkg.devDependencies };

  // Framework detection
  let framework: ProjectConfig["framework"] = "unknown";
  if (deps["next"]) framework = "nextjs";
  else if (deps["vite"]) framework = "vite";
  else if (deps["@remix-run/node"] || deps["@remix-run/react"]) framework = "remix";

  // TypeScript detection
  const typescript = !!(deps["typescript"] || await fs.pathExists(path.join(cwd, "tsconfig.json")));

  // Tailwind detection
  const tailwind = !!(deps["tailwindcss"] || await fs.pathExists(path.join(cwd, "tailwind.config.js")) || await fs.pathExists(path.join(cwd, "tailwind.config.ts")));

  // src dir detection
  const srcDir = await fs.pathExists(path.join(cwd, "src"));

  // Package manager detection
  let packageManager: ProjectConfig["packageManager"] = "npm";
  if (await fs.pathExists(path.join(cwd, "bun.lockb"))) packageManager = "bun";
  else if (await fs.pathExists(path.join(cwd, "pnpm-lock.yaml"))) packageManager = "pnpm";
  else if (await fs.pathExists(path.join(cwd, "yarn.lock"))) packageManager = "yarn";

  // Components directory
  const candidateDirs = [
    path.join(cwd, srcDir ? "src" : "", "components"),
    path.join(cwd, "components"),
  ];
  let componentsDir = candidateDirs[0];
  for (const dir of candidateDirs) {
    if (await fs.pathExists(dir)) { componentsDir = dir; break; }
  }

  return { root: cwd, framework, typescript, tailwind, srcDir, componentsDir, packageManager };
}

// ─── Dependency installer ─────────────────────────────────────────────────────

async function installDeps(deps: string[], config: ProjectConfig) {
  const pkgPath = path.join(config.root, "package.json");
  const pkg = await fs.readJson(pkgPath).catch(() => ({ dependencies: {} }));
  const existing = { ...pkg.dependencies, ...pkg.devDependencies };

  const toInstall = deps.filter((d) => !existing[d]);
  if (toInstall.length === 0) return;

  const spinner = ora(`Installing ${toInstall.join(", ")}…`).start();

  const installCmd = {
    npm: ["npm", "install", "--save"],
    pnpm: ["pnpm", "add"],
    yarn: ["yarn", "add"],
    bun: ["bun", "add"],
  }[config.packageManager];

  try {
    await execa(installCmd[0], [...installCmd.slice(1), ...toInstall], { cwd: config.root });
    spinner.succeed(chalk.green(`Installed: ${toInstall.join(", ")}`));
  } catch {
    spinner.fail(chalk.red(`Failed to install deps. Run manually: ${installCmd[0]} add ${toInstall.join(" ")}`));
  }
}

// ─── File fetcher ────────────────────────────────────────────────────────────

async function fetchComponentFile(name: ComponentName, typescript: boolean): Promise<string> {
  const ext = typescript ? "tsx" : "jsx";
  const url = `${REGISTRY_BASE}/${name}/component.${ext}`;
  const res = await fetch(url);
  if (!res.ok) {
    // fallback: generate a stub
    return generateComponentStub(name, typescript);
  }
  return res.text();
}

function generateComponentStub(name: ComponentName, typescript: boolean): string {
  const componentName = name
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");

  if (typescript) {
    return `"use client";

/**
 * ${componentName}
 * Generated by Frosted UI CLI v1.0.0
 * 
 * Docs: https://frosted-ui.dev/docs/${name}
 */

import { motion } from "framer-motion";
import { cn } from "@/lib/utils";

export interface ${componentName}Props {
  className?: string;
}

export function ${componentName}({ className }: ${componentName}Props) {
  return (
    <motion.div
      className={cn(
        "relative rounded-3xl",
        "backdrop-blur-2xl saturate-[180%]",
        "bg-white/[0.07] border border-white/[0.12]",
        "shadow-[0_8px_32px_rgba(0,0,0,0.4)]",
        className
      )}
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
    >
      {/* Frosted glass reflection layer */}
      <div className="absolute inset-0 rounded-[inherit] bg-gradient-to-b from-white/[0.06] to-transparent pointer-events-none" />
      {/* TODO: implement ${componentName} */}
      <div className="p-4 text-sm text-white/60">${componentName}</div>
    </motion.div>
  );
}

export default ${componentName};
`;
  }

  return `"use client";
import { motion } from "framer-motion";

export function ${componentName}({ className }) {
  return (
    <motion.div className={\`relative rounded-3xl backdrop-blur-2xl bg-white/[0.07] border border-white/[0.12] \${className}\`}
      initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
      <div className="p-4 text-sm text-white/60">${componentName}</div>
    </motion.div>
  );
}
export default ${componentName};
`;
}

// ─── ADD command ─────────────────────────────────────────────────────────────

async function addComponent(names: string[], options: { cwd: string; overwrite?: boolean }) {
  const cwd = path.resolve(options.cwd ?? process.cwd());

  console.log(chalk.bold.white("\n✦ Frosted UI\n"));

  // Validate
  const invalid = names.filter((n) => !COMPONENTS.includes(n as ComponentName));
  if (invalid.length) {
    console.error(chalk.red(`Unknown component(s): ${invalid.join(", ")}`));
    console.log(chalk.gray(`Available: ${COMPONENTS.join(", ")}`));
    process.exit(1);
  }

  // Detect project
  const spinner = ora("Detecting project…").start();
  const config = await detectProject(cwd);
  spinner.succeed(chalk.gray(
    `${chalk.white(config.framework)} · ${config.typescript ? "TypeScript" : "JavaScript"} · ${config.tailwind ? "Tailwind ✓" : "No Tailwind"} · ${config.packageManager}`
  ));

  if (!config.tailwind) {
    console.warn(chalk.yellow("⚠ Tailwind CSS not detected. Frosted UI requires Tailwind CSS v3+."));
  }

  // Ensure components dir exists
  if (!(await fs.pathExists(config.componentsDir))) {
    await fs.mkdirp(config.componentsDir);
    console.log(chalk.gray(`Created: ${path.relative(cwd, config.componentsDir)}/`));
  }

  // Install all needed deps (union of all selected components)
  const allDeps = new Set(["framer-motion", "lucide-react", "class-variance-authority", "clsx", "tailwind-merge"]);
  await installDeps([...allDeps], config);

  // Add each component
  for (const name of names) {
    const compSpinner = ora(`Adding ${chalk.white(name)}…`).start();

    try {
      const ext = config.typescript ? "tsx" : "jsx";
      const destFile = path.join(config.componentsDir, `${name}.${ext}`);

      if ((await fs.pathExists(destFile)) && !options.overwrite) {
        const { overwrite } = await prompts({
          type: "confirm",
          name: "overwrite",
          message: `${name}.${ext} already exists. Overwrite?`,
          initial: false,
        });
        if (!overwrite) { compSpinner.warn(chalk.yellow(`Skipped: ${name}`)); continue; }
      }

      const content = await fetchComponentFile(name as ComponentName, config.typescript);
      await fs.outputFile(destFile, content);

      compSpinner.succeed(
        `${chalk.green("Added")} ${chalk.white(path.relative(cwd, destFile))}`
      );
    } catch (err) {
      compSpinner.fail(chalk.red(`Failed to add ${name}: ${err}`));
    }
  }

  // Summary
  console.log(chalk.bold.white("\n✦ Done!\n"));
  console.log(chalk.gray("Import your component:"));
  for (const name of names) {
    const componentName = name.split("-").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join("");
    const importPath = `@/components/${name}`;
    console.log(chalk.cyan(`  import { ${componentName} } from "${importPath}";`));
  }
  console.log();
}

// ─── LIST command ─────────────────────────────────────────────────────────────

function listComponents() {
  console.log(chalk.bold.white("\n✦ Frosted UI — Available Components\n"));

  const categories: Record<string, ComponentName[]> = {
    "Navigation Bars": ["floating-island-bar", "pill-bar", "arc-bar", "crystal-bar", "ribbon-bar", "wave-bar"],
    "Pebble & Dock": ["pebble-bar", "dock-bar"],
    "Expandable Sheets": ["expandable-nav-sheet", "command-sheet", "profile-sheet"],
    "Floating Elements": ["app-launcher", "floating-search-orb", "floating-action-button", "floating-command-bar"],
  };

  for (const [category, components] of Object.entries(categories)) {
    console.log(chalk.bold.white(`  ${category}`));
    for (const name of components) {
      console.log(chalk.gray(`    npx frosted-ui add ${name}`));
    }
    console.log();
  }
}

// ─── CLI Setup ────────────────────────────────────────────────────────────────

const program = new Command()
  .name("frosted-ui")
  .description("Frosted UI — Add frosted glass components to your React project")
  .version("1.0.0");

program
  .command("add", { isDefault: true })
  .description("Add a component to your project")
  .argument("<components...>", "component name(s) to add")
  .option("--cwd <dir>", "working directory", process.cwd())
  .option("--overwrite", "overwrite existing files", false)
  .action(addComponent);

program
  .command("list")
  .description("List all available components")
  .action(listComponents);

program
  .command("init")
  .description("Initialize Frosted UI in your project (installs base deps)")
  .option("--cwd <dir>", "working directory", process.cwd())
  .action(async (options) => {
    const cwd = path.resolve(options.cwd ?? process.cwd());
    const config = await detectProject(cwd);
    await installDeps(["framer-motion", "lucide-react", "class-variance-authority", "clsx", "tailwind-merge"], config);
    console.log(chalk.bold.green("\n✦ Frosted UI initialized! Run `npx frosted-ui list` to see components.\n"));
  });

program.parse();
